module.exports = ["(AGRIBANK) Nông nghiệp và phát triển nông thôn Việt Nam",
"(BIDV) Đầu tư và phát triển Việt Nam",
"(VIETINBANK) Công Thương Việt Nam",
"(VPBANK) Việt Nam Thịnh Vượng",
"(ABBANK) An Bình",
"(ACB) Á Châu",
"(BAC A) Bắc Á",
"(BAO VIET BANK) Bảo Việt",
"(CBBANK) Ngân hàng Xây dựng ",
"(CIMB) CIMB Bank Việt Nam",
"(DONG A BANK) Đông Á",
"(EXIMBANK) Xuất Nhập khẩu",
"(GPBANK) Dầu khí toàn cầu",
"(HD BANK) Phát triển TP.HCM",
"(HLBANK) Hong Leong Việt Nam",
"(HSBC) TNHH MTV HSBC Việt Nam ",
"(IBK Bank) Công nghiệp Hàn Quốc ",
"(IVB) Trách nhiệm hữu hạn Indovina",
"(KIEN LONG BANK) Kiên Long",
"(LIEN VIET POST BANK) Bưu điện Liên Việt",
"(MB) Quân Đội",
"(MSB - MARITIME BANK) Hàng Hải",
"(NAM A BANK) Nam Á",
"(NCB) Quốc Dân",
"(NHB) Nonghuyp - Chi nhánh Hà Nội",
"(OCB) Phương Đông",
"(OCEANBANK) Đại dương",
"(PGBANK) Xăng Dầu Petrolimex",
"(PUBLIC BANK) Đại chúng Việt Nam",
"(PVCOMBANK) Đại chúng",
"(SACOMBANK) Sài Gòn thương tín",
"(SAIGONBANK) Sài Gòn Công Thương",
"(SCB) Sài Gòn",
"(SCVN) TNHH MTV Standard Chartered Việt Nam ",
"(SEABANK) Đông Nam Á",
"(SHB) Sài Gòn Hà Nội",
"(SHINHAN) Shinhan Bank Việt Nam",
"(TECHCOMBANK) Kỹ thương Việt Nam",
"(TPBANK) Tiên phong",
"(UOB VN) UOB Việt Nam",
"(VIB) Quốc tế",
"(VIET A BANK) Việt Á",
"(VIET CAPITAL BANK) Bản Việt",
"(VIETBANK) Việt Nam Thương Tín"]